apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dev-web-botilyx
  namespace: aplicaciones
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: dev-web-botilyx

