apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dev-web-botilyx-hpa
  namespace: aplicaciones
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-web-botilyx
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max

