apiVersion: v1
kind: ConfigMap
metadata:
  name: botilyx-config
  namespace: botilyx
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  # Configurar según tu despliegue
  NEXT_PUBLIC_BASE_PATH: ""
  FORCE_HTTPS: "true"
