apiVersion: v1
kind: Secret
metadata:
  name: botilyx-secrets
  namespace: botilyx
type: Opaque
stringData:
  # Configurar con tus valores reales
  DATABASE_URL: "postgresql://username:password@postgres-service:5432/botilyx_prod"
  SESSION_SECRET: "your-super-secret-session-key-for-production"
  GEMINI_API_KEY: "your-gemini-api-key"
  VAPID_PUBLIC_KEY: "your-vapid-public-key"
  VAPID_PRIVATE_KEY: "your-vapid-private-key"
  NOTIFICATION_PROCESSOR_SECRET: "your-notification-processor-secret"
  SMTP_HOST: ""
  SMTP_PORT: ""
  SMTP_USER: ""
  SMTP_PASS: ""
  REDIS_URL: ""
